// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR5zos04-OfgCewo8NYgP09ANXT9tqgiI',
    appId: '1:824302818982:web:6d9f48fb12acbfa4ca4667',
    messagingSenderId: '824302818982',
    projectId: 'pacanga-a586f',
    authDomain: 'pacanga-a586f.firebaseapp.com',
    storageBucket: 'pacanga-a586f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJph1tuTtOgKYXHlRMNEacdHq98peydw',
    appId: '1:824302818982:android:69b5bba275afb6e7ca4667',
    messagingSenderId: '824302818982',
    projectId: 'pacanga-a586f',
    storageBucket: 'pacanga-a586f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsuwbwpidddQhJQBRPR5CiQ3I-MM2gvY8',
    appId: '1:824302818982:ios:533e2c62880b20ecca4667',
    messagingSenderId: '824302818982',
    projectId: 'pacanga-a586f',
    storageBucket: 'pacanga-a586f.firebasestorage.app',
    iosBundleId: 'com.example.digiadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsuwbwpidddQhJQBRPR5CiQ3I-MM2gvY8',
    appId: '1:824302818982:ios:533e2c62880b20ecca4667',
    messagingSenderId: '824302818982',
    projectId: 'pacanga-a586f',
    storageBucket: 'pacanga-a586f.firebasestorage.app',
    iosBundleId: 'com.example.digiadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR5zos04-OfgCewo8NYgP09ANXT9tqgiI',
    appId: '1:824302818982:web:f894cb2dc78c92ebca4667',
    messagingSenderId: '824302818982',
    projectId: 'pacanga-a586f',
    authDomain: 'pacanga-a586f.firebaseapp.com',
    storageBucket: 'pacanga-a586f.firebasestorage.app',
  );
}
